# backend/src/main/resources/application.yml
spring:
  application:
    name: ai-security-monitor

  datasource:
    url: jdbc:postgresql://localhost:5432/securemonitor
    username: securemonitor
    password: localdev123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: optional:file:.env[.properties]

server:
  port: 8080

groq:
  api-key: ${GROQ_API_KEY:}
  model: llama-3.1-8b-instant
