# backend/src/main/resources/application.yml
spring:
  application:
    name: ai-security-monitor

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/securemonitor}
    username: ${PGUSER:securemonitor}
    password: ${PGPASSWORD:localdev123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

groq:
  api-key: ${GROQ_API_KEY:}
  model: llama-3.1-8b-instant
